In [1]:
import sys

sys.path.append("..")
from fireballpy import Fireball
from ase.io import read

ImportError: cannot import name 'NDArray' from 'numpy.typing' (/opt/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/numpy/typing/__init__.py)

In [ ]:
atoms = read("input.xyz")
atoms.calc = Fireball()

In [3]:
ETOT=atoms.get_potential_energy()

   EBS =      -86.325363 ; Kscf =   1 ; sigma =0.7032531286
   EBS =      -85.349226 ; Kscf =   2 ; sigma =0.6267393232
   EBS =      -71.237392 ; Kscf =   3 ; sigma =0.0199099731
   EBS =      -71.923123 ; Kscf =   4 ; sigma =0.0162023626
   EBS =      -74.856191 ; Kscf =   5 ; sigma =0.0000091974
   EBS =      -74.861009 ; Kscf =   6 ; sigma =0.0000078584
   EBS =      -74.837389 ; Kscf =   7 ; sigma =0.0000030467
   EBS =      -74.799083 ; Kscf =   8 ; sigma =0.0000000054


In [4]:
print("ETOT =",ETOT)

ETOT = -211.4897003173828


In [5]:
charge=atoms.get_charges()
print("------atoms.charges-----------")
for c in charge:
  print(c)

------atoms.charges-----------
[1.17506731 3.3786602 ]
[8.15296292e-001 6.90012172e-310]
[8.76992047e-001 6.90012172e-310]
[8.76992047e-001 6.90012172e-310]
[8.76992047e-001 6.90012172e-310]


In [7]:
force=atoms.get_forces()
print("------atoms.forces------------")
for f in force:
  print(f)


------atoms.forces------------
[4.63579273 4.63579273 4.63579273]
[2.13388157 2.13388157 2.13388157]
[-2.53655553 -2.11655927 -2.11655927]
[-2.11655927 -2.53655553 -2.11655927]
[-2.11655951 -2.11655951 -2.53655529]
