In [1]:
import sys
import numpy as np
sys.path.append("..")
from fireballpy import Fireball
from ase import Atoms

In [2]:
atoms = Atoms(symbols=['C', 'H', 'H', 'H', 'H'],
            positions=[( 0.0000, 0.0000, 0.0000),
                       ( 0.6533, 0.6533, 0.6533),
                       (-0.6533, 0.6533, 0.6533),
                       ( 0.6533, -0.6533, 0.6533),
                       ( 0.6533, 0.6533, -0.6533)])

In [3]:
atoms.calc = Fireball(charges_method='Mulliken-dipole-preserving', options='molecule')

In [4]:
ETOT=atoms.get_potential_energy()
print(ETOT)

-211.70370382918276


In [5]:
charge=atoms.get_charges()
print("------atoms.charges-----------")
print(charge)
#for c in charge:
#  print(c)

------atoms.charges-----------
[4.4692962  0.5884139  0.98076324 0.98076324 0.98076341]


In [6]:
force=atoms.get_forces()
print("------atoms.forces------------")
for f in force:
  print(f)


------atoms.forces------------
[4.93096081 4.93096081 4.93096061]
[2.39933365 2.39933365 2.39933357]
[-2.86792482 -2.23118486 -2.23118471]
[-2.23118486 -2.86792482 -2.23118471]
[-2.23118477 -2.23118477 -2.86792475]
