In [1]:
%pip install ase
import sys
import os
from fireballpy import Fireball
from ase.io import read

In [2]:
atoms = read("input.xyz")
atoms.calc = Fireball(fdata_path="Fdata_HC/")

In [3]:
ETOT = atoms.get_potential_energy()
print(ETOT)

-214.91729736328125


In [4]:
atoms.get_charges()
atoms.get_potential_energy()
atoms.get_forces()


      1.06487367    2.78622435    0.19226561
      0.92242015    0.02417989
      0.99328238    0.01006288
      0.99328240    0.01006291
      0.99328281    0.01006295


array([[ 3.36838359,  3.36838192,  3.36838809],
       [ 1.6870016 ,  1.68700188,  1.68699881],
       [-1.86120502, -1.59708746, -1.59709139],
       [-1.59708752, -1.86120253, -1.59709472],
       [-1.59709266, -1.59709381, -1.8612008 ]])

  The grand total force (eV/A): 
   iatom =    1 ftot      =   0.336838E+01  0.336838E+01  0.336839E+01
   iatom =    2 ftot      =   0.168700E+01  0.168700E+01  0.168700E+01
   iatom =    3 ftot      =  -0.186121E+01 -0.159709E+01 -0.159709E+01
   iatom =    4 ftot      =  -0.159709E+01 -0.186120E+01 -0.159709E+01
   iatom =    5 ftot      =  -0.159709E+01 -0.159709E+01 -0.186120E+01


In [ ]:
atoms.get_forces()

In [18]:
import numpy as np
n=10
foces = np.zeros((n,3 ))
foces[5,1]=10.0

In [19]:
print(foces)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
